management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
#    git:
#      mode: full #git ??? ??
  server:
    port: 8080
  endpoint:
    shutdown:
      enabled: true # ????? ???
    health:
#      show-details: always  # ??? ??
      show-components: always # ??? ??
  endpoints:
    web:
      exposure:
        include: "*" # ?? ?????? ?? ??
info: # application ?? ???? ????? info ?? ?????? ?? ??.
  app:
    name: hello-actuator
    company: by

logging:
  level:
    hello.controller: debug
server:
  tomcat:
    mbeanregistry:
      enabled: true
